### ISSUE TITLE
Allow a Second Column of Styles

### ISSUE THREAD

**Issue by jprovasnik** [moodleuulm/moodle-atto_styles#14]
We love this plug in - unfortunately, we have filled it up already. The list is so long that we cannot scroll down to the bottom. Any way to get the list to appear in two columns instead of one?
<img width="543" alt="list of styles" src="https://user-images.githubusercontent.com/44345287/52567886-56459800-2ddb-11e9-8756-0fa8ab83ec99.png">

**Comment by abias** [comment]
Hi @jprovasnik ,

thank you for reporting this issue.

I have to admit that we haven't tested the plugin yet with so many styles, but you are right to say that this may happen.

I didn't want to introduce a second column (because anytime in the future, someone will need a third column and so on), so I just made sure that the dropdown does not grow longer than the current height of the Atto element.

This was commited on https://github.com/moodleuulm/moodle-atto_styles/commit/d01668510ad70b571fe4fbdeb96019282092693b and a new version will be released shortly to the Moodle plugins repo.

Cheers,
Alex
