### ISSUE TITLE
Feedback with Moodle 3.9.3+ (Build: 20210108)

### ISSUE THREAD

**Issue by clementpr** [moodleuulm/moodle-atto_styles#23]
Hi,

Thank you for the style plugin that we use regularly with great success. 
We discovered a bug with this week's version of Moodle 3.9. It is no longer possible to configure the style without modifying the text. We use "v3.8-r2" version of the plugin.

Case 1: added the usual style: JSON error
![image](https://user-images.githubusercontent.com/8448884/104725668-b0230b00-5732-11eb-8d0d-abcc7913fc17.png)

Case 2 : added style with [ and ] > OK
![image](https://user-images.githubusercontent.com/8448884/104725735-c630cb80-5732-11eb-9e7d-8df5fcf83f47.png)

Clément

**Comment by abias** [comment]
Hi @clementpr ,

I am sorry that this issue remained unanswered for so long.

In version 3.8-r2, we introduced a JSON validation for the plugin's settings which came with the requirement that the JSON has to be valid. As soon as you add multiple styles, you have to surround the configuration with square brackets. We introduced an upgrade script for existing installations, we changed the explanations in the language pack and we wrote a note in CHANGES.md (see https://github.com/moodle-an-hochschulen/moodle-atto_styles/blob/MOODLE_39_STABLE/CHANGES.md#v38-r2) about this fact.

So, in the end, you did everything right by adding square brackets and this isn't a bug but intentional behaviour.

Cheers,
Alex
