### ISSUE TITLE
"styles" cannot be used

### ISSUE THREAD

**Issue by StacyZhangUEA** [moodleuulm/moodle-atto_styles#29]
https://user-images.githubusercontent.com/97592254/149091897-410df10f-cc97-4d24-ad30-87cc01ce1c4c.mp4

Hi, the plugin "styles" cannot be used suddenly. How can I solve this issue>

**Comment by abias** [comment]
Hi @StacyZhangUEA 

I am sorry that this issue remained unanswered for so long.

Looking at your screencast, I see that the styles plugin does not work, but nothing more.

Did you add the CSS code corresponding to the styles plugin configuration to your Moodle site's custom CSS as it's explained in the plugins README?
Which Moodle version, which plugin version and which browser are you using?

Given the fact that this issue is nearly a year old, I am going to close this now, but please come back if the problem still exists for you.

Cheers,
Alex
